" Note: Skip initialization for vim-tiny or vim-small.
if !1 | finish | endif

filetype plugin indent on
set encoding=utf8
set fileformat=unix
set modelines=0
set autoindent
set showcmd
set hidden
set visualbell
set ttyfast
set ruler
set backspace=indent,eol,start
set number
set laststatus=2
set history=1000
set undoreload=10000
set shell=zsh
set lazyredraw
set matchtime=3
set showbreak=↪
set splitbelow
set splitright
set fillchars=diff:⣿,vert:│
set autowrite
set autoread
set shiftround
set title
set linebreak
set cursorline
set tabpagemax=50
set noshowmode
let mapleader = ","

" Column highlight
set colorcolumn=+1
let &colorcolumn="+1,".join(range(120,999),",")

set ttimeout
set ttimeoutlen=50

" Remember vim status on close
set viminfo='100,<1000,s100,%,:5

" scrolling
set scrolloff=3
set sidescroll=1
set sidescrolloff=10

"Set font type and size. Depends on the resolution. Larger screens, prefer h20
set guifont=Inconsolata\ for\ Powerline:h16

" Better Completion
set completeopt=longest,menuone,preview

" Resize splits when the window is resized
au VimResized * :wincmd =
"
" tabs and spaces
set expandtab
set smarttab
set tabstop=8
set softtabstop=4
set shiftwidth=4
au BufNewFile,BufReadPost *.css,*.html,*.mako,*.rb,*.erb,*.coffee,*.js,*.json set shiftwidth=2

" other visuals
set wildmenu
set wildmode=list:longest
set wildignore+=.hg,.git,.svn                    " Version control
set wildignore+=*.jpg,*.bmp,*.gif,*.png,*.jpeg   " binary images
set wildignore+=*.o,*.obj,*.exe,*.dll,*.manifest " compiled object files
set wildignore+=*.spl                            " compiled spelling word lists
set wildignore+=*.sw?                            " Vim swap files
set wildignore+=*.DS_Store                       " OSX bullshit
set wildignore+=migrations                       " Django migrations
set wildignore+=*.pyc                            " Python byte code
set wildignore+=*.orig                           " Merge resolution files

" folds
set foldlevel=0

"Better line wrapping
set wrap
set textwidth=80
set formatoptions=qrn1

" search
set ignorecase
set smartcase
set incsearch
set showmatch
set hlsearch

" Press Space to turn off highlighting and clear any message already displayed.
:nnoremap <silent> <Space> :nohlsearch<Bar>:echo<CR>

" Spellcheck with vim (set spell / set nospell)
set dictionary=/usr/share/dict/words
set spellfile=~/.vim/custom-dictionary.utf-8.add
syn spell toplevel

" Automatically reload vimrc
autocmd! bufwritepost vimrc source ~/.vimrc

" Other mappings
nnoremap Y y$
map <C-j> :bn<cr>
map <C-k> :bp<cr>

" Backups
set undodir=~/.vim/tmp/undo//     " undo files
set backupdir=~/.vim/tmp/backup// " backups
set directory=~/.vim/tmp/swap//   " swap files
set undofile
set backup                        " enable backups
set noswapfile                    " It's 2012, Vim.

" Use the below highlight group when displaying bad whitespace is desired
highlight BadWhitespace ctermbg=red guibg=red

" Make trailing whitespace be flagged as bad.
au BufRead,BufNewFile *.py,*.pyw,*.c,*.h match BadWhitespace /\s\+$/
au BufRead,BufNewFile *.py,*.pyw match BadWhitespace /^\t\+/

" shortcuts and abbreviations
abbreviate pdbst import pdb;pdb.set_trace()
abbreviate lorem Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
" Remove whitespace on lines end
nnoremap <leader>w :%s/\s\+$//<cr>:let @/=''<CR>
"
" Toggle [i]nvisible characters
nnoremap <leader>i :set list!<cr>
set listchars=tab:▸\ ,eol:¬,extends:❯,precedes:❮

" Emacs bindings in command line mode
cnoremap <c-a> <home>
cnoremap <c-e> <end>

if has('gui_running')

    " Remove all the UI cruft
    set go-=T
    set go-=l
    set go-=L
    set go-=r
    set go-=R
    set foldenable
    set so=7

    " Different cursors for different modes.
    highlight Cursor guifg=black guibg=green
    highlight iCursor guifg=white guibg=steelblue
    set guicursor=n-v-c:block-Cursor
    set guicursor+=i:ver100-iCursor
    set guicursor+=n-v-c:blinkon0
    set guicursor+=i:blinkwait10

    if has("gui_macvim")
        " Full screen means FULL screen
        set fuoptions=maxvert,maxhorz

        " free up Command-F and toggle fullscreen mode
        macmenu &Edit.Find.Find\.\.\. key=<nop>
        map <D-f> :set invfu<CR>

        " Use the normal HIG movements, except for M-Up/Down
        let macvim_skip_cmd_opt_movement = 1
        no   <D-Left>       <Home>
        no!  <D-Left>       <Home>
        no   <M-Left>       <C-Left>
        no!  <M-Left>       <C-Left>

        no   <D-Right>      <End>
        no!  <D-Right>      <End>
        no   <M-Right>      <C-Right>
        no!  <M-Right>      <C-Right>

        no   <D-Up>         <C-Home>
        ino  <D-Up>         <C-Home>
        imap <M-Up>         <C-o>{

        no   <D-Down>       <C-End>
        ino  <D-Down>       <C-End>
        imap <M-Down>       <C-o>}

        imap <M-BS>         <C-w>
        inoremap <D-BS>     <esc>my0c`y
    else
        " Non-MacVim GUI, like Gvim
    end
else
    " Console Vim
    " For me, this means iTerm2, possibly through tmux
    " Mouse support
    set mouse=a
endif

" Use Node.js for JavaScript interpretation
let $JS_CMD='node'

if has('vim_starting')
  set nocompatible               " Be iMproved

  " Required:
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

" Required:
call neobundle#begin(expand('~/.vim/bundle/'))

" Let NeoBundle manage NeoBundle
" Required:
NeoBundleFetch 'Shougo/neobundle.vim'

" Bundles
NeoBundle 'Shougo/vimproc.vim', {
\ 'build' : {
\     'windows' : 'tools\\update-dll-mingw',
\     'cygwin' : 'make -f make_cygwin.mak',
\     'mac' : 'make -f make_mac.mak',
\     'linux' : 'make',
\     'unix' : 'gmake',
\    },
\ }
NeoBundle 'flazz/vim-colorschemes'
NeoBundle 'bling/vim-airline'
NeoBundle 'airblade/vim-gitgutter'
NeoBundle 'kien/ctrlp.vim'
NeoBundle 'mbbill/undotree'
NeoBundle 'majutsushi/tagbar'
NeoBundle 'scrooloose/nerdtree'
NeoBundle 'scrooloose/syntastic'
NeoBundle 'myusuf3/numbers.vim'
NeoBundle 'msanders/snipmate.vim'
NeoBundle 'tristen/vim-sparkup'
NeoBundle 'tsaleh/vim-supertab'
NeoBundle 'tpope/vim-abolish'
NeoBundle 'tpope/vim-fugitive'
NeoBundle 'tpope/vim-commentary'
NeoBundle 'tpope/vim-surround'
NeoBundle 'tpope/vim-eunuch'
NeoBundle 'tpope/vim-repeat'
NeoBundle 'tpope/vim-git'
NeoBundle 'tpope/vim-haml'
NeoBundle 'tpope/vim-markdown'
NeoBundle 'nelstrom/vim-markdown-preview'
NeoBundle 'klen/python-mode'
NeoBundle 'jmcantrell/vim-virtualenv'
NeoBundle 'sophacles/vim-bundle-mako'
NeoBundle 'jnwhiteh/vim-golang'
NeoBundle 'pangloss/vim-javascript'
NeoBundle 'kchmck/vim-coffee-script'
NeoBundle 'vim-scripts/vim-json-bundle'
NeoBundle 'derekwyatt/vim-scala'
NeoBundle 'rizzatti/funcoo.vim'
NeoBundle 'nathanaelkane/vim-indent-guides'
NeoBundle 'santiycr/grin.vim'
NeoBundle 'jiangmiao/auto-pairs'
NeoBundle 'chrisbra/NrrwRgn'
NeoBundle 'Lokaltog/vim-easymotion'
NeoBundle 'maxbrunsfeld/vim-yankstack'
NeoBundle 'godlygeek/tabular'
" NeoBundle 'editorconfig/editorconfig-vim'
if has("mac")
    NeoBundle 'rizzatti/dash.vim'
    set macmeta
endif
call neobundle#end()

" Airline
let g:airline_powerline_fonts=1
let g:airline_theme='solarized'
let g:airline_exclude_filenames = ['DebuggerWatch', 'DebuggerStack', 'DebuggerStatus']
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#buffer_min_count = 2
let g:airline#extensions#tabline#buffer_nr_show = 1
let g:airline#extensions#tabline#formatter = 'unique_tail'
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
let g:bufferline_echo=0

" python tweaks
let g:pymode_folding = 0
let g:pymode_rope = 1
let g:pymode_rope_complete_on_dot = 1
let g:pymode_lint = 1
let g:pymode_lint_on_write = 0
let g:pymode_lint_error_symbol = '✗'
let g:pymode_lint_todo_symbol = '⚠'
let g:pymode_virtualenv = 1
let g:syntastic_error_symbol = '✗'
let g:syntastic_warning_symbol = '⚠'
let g:syntastic_enable_balloons = 0
" close preview window (used for docs) once insert is done
autocmd InsertLeave * :pc

" tagbar config
let g:tagbar_autoshowtag = 1

" Indent guides
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_color_change_percent = 2

" Dash
nmap <silent> <leader>d <Plug>DashSearch

" CtrlP
set runtimepath^=~/.vim/bundle/ctrlp.vim

"Color scheme
let g:solarized_hitrail=1    "default value is 0
syntax enable
set background=dark
colorscheme solarized
let g:solarized_termcolors=256
let g:solarized_menu=0

" Undotree window
nnoremap <leader>u :UndotreeToggle<CR>
" Tagbar window
nnoremap <leader>t :TagbarToggle<CR>
" Grin for the last search.
nnoremap <silent> <leader>grin :execute "GrinFromSearch!"<CR>


" nerdtree
nnoremap <leader>n :NERDTreeToggle<CR>

map <Leader>s <Plug>(easymotion-s2)

" Turn on case sensitive feature
let g:EasyMotion_smartcase = 1

" JK motions: Line motions
map <Leader>j <Plug>(easymotion-j)
map <Leader>k <Plug>(easymotion-k)

" Installation check.
NeoBundleCheck
