# load zgen
source "${HOME}/.zgen/zgen.zsh"

# if the init scipt doesn't exist
if ! zgen saved; then
    echo "Creating a zgen save"

    zgen prezto prompt theme 'pure'
    zgen prezto
    zgen prezto node
    zgen prezto git
    zgen prezto python
    zgen prezto osx
    zgen prezto spectrum
    zgen prezto tmux

    zgen load chrissicool/zsh-256color
    zgen load willghatch/zsh-saneopt
    zgen load supercrabtree/k
    zgen load hkupty/ssh-agent
    zgen load iam4x/zsh-iterm-touchbar
    zgen load zsh-users/zsh-autosuggestions
    zgen load zdharma/fast-syntax-highlighting
    zgen load sei40kr/zsh-tmux-rename
    zgen load laurenkt/zsh-vimto
    zgen load hlissner/zsh-autopair
    zgen load MichaelAquilina/zsh-autoswitch-virtualenv
    zgen load zdharma/history-search-multi-word
    zgen load robertzk/send.zsh
    zgen load mattbangert/kubectl-zsh-plugin
    zgen load littleq0903/gcloud-zsh-completion
    zgen load unixorn/autoupdate-zgen

    # save all to init script
    zgen save
fi

unsetopt AUTO_NAME_DIRS       # Dont auto add variable-stored paths to ~ list.
bindkey "^R" history-search-multi-word

# Path setups
export PATH=$HOME/bin:/usr/X11/bin:$PATH
export PATH=$(brew --prefix coreutils)/libexec/gnubin:$PATH
export PATH=$PATH:$HOME/.gem/ruby/2.4.0/bin
# user pip installs
export PATH=$PATH:$HOME/Library/Python/2.7/bin
export PATH=$PATH:$HOME/Library/Python/3.5/bin
# npm
export PATH=$PATH:/usr/local/share/npm/bin

# Custom setups
if [ -e $HOME/setenv.sh ]; then
    . $HOME/setenv.sh
fi

# enable z installed via brew
. `brew --prefix`/etc/profile.d/z.sh

# switch to neovim for my editor
export EDITOR=nvim

# added by travis gem
[ -f /Users/santiagosuarezordonez/.travis/travis.sh ] && source /Users/santiagosuarezordonez/.travis/travis.sh

# virtualenv setup
export WORKON_HOME=~/.virtualenvs
source $HOME/Library/Python/2.7/bin/virtualenvwrapper_lazy.sh

alias mux=tmuxinator

