export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

zplug "chrissicool/zsh-256color"
zplug "djui/alias-tips"
zplug "supercrabtree/k"
zplug "sharat87/pip-app"
zplug "hkupty/ssh-agent"
zplug "iam4x/zsh-iterm-touchbar"
zplug "zlsun/solarized-man"
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-completions"
zplug "zdharma/fast-syntax-highlighting"
zplug "zdharma/history-search-multi-word", defer:1
zplug "sei40kr/zsh-tmux-rename", if:"[ -n "$TMUX" ]"
zplug "modules/completion",   from:prezto
zplug "modules/environment", from:prezto
zplug "modules/terminal", from:prezto
zplug "modules/node", from:prezto
zplug "modules/git", from:prezto
zplug "modules/python", from:prezto
zplug "modules/osx", from:prezto
zplug "modules/history", from:prezto
zplug "modules/directory", from:prezto
zplug "modules/spectrum", from:prezto
zplug "modules/utility", from:prezto
zplug "modules/tmux", from:prezto
zplug "plugins/aws",   from:oh-my-zsh
zplug "plugins/vi-mode",   from:oh-my-zsh

# Install plugins if there are plugins that have not been installed
# if ! zplug check; then
#     printf "Install? [y/N]: "
#     if read -q; then
#         echo; zplug install
#     fi
# fi

# Then, source plugins and add commands to $PATH
zplug load

zstyle :omz:plugins:ssh-agent agent-forwarding on
export HISTFILE=~/.zhistory

# Path setups
export PATH=$HOME/bin:$HOME/.venvburrito/bin:$HOME/.rvm/bin:/usr/local/bin:/usr/local/sbin:/usr/X11/bin:$PATH
export PATH=$(brew --prefix coreutils)/libexec/gnubin:$PATH
# user pip installs
export PATH=$PATH:$HOME/Library/Python/2.7/bin
export PATH=$PATH:$HOME/Library/Python/3.5/bin
# npm
export PATH=$PATH:/usr/local/share/npm/bin

# Custom setups
if [ -e $HOME/setenv.sh ]; then
    . $HOME/setenv.sh
fi

# enable z installed via brew
. `brew --prefix`/etc/profile.d/z.sh
#
# Make ondir work
eval_ondir() {
  eval "`ondir \"$OLDPWD\" \"$PWD\"`"
}
chpwd_functions=( eval_ondir $chpwd_functions )
autoload -U promptinit; promptinit
prompt pure
KEYTIMEOUT=1
export EDITOR=nvim

# added by travis gem
[ -f /Users/santiagosuarezordonez/.travis/travis.sh ] && source /Users/santiagosuarezordonez/.travis/travis.sh
